
package cn.com.ips.payat.webservice.orderquery;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSOrderQuery", targetNamespace = "http://payat.ips.com.cn/WebService/OrderQuery", wsdlLocation = "https://newpay.ips.com.cn/psfp-entry/services/order?wsdl")
public class WSOrderQuery
    extends Service
{

    private final static URL WSORDERQUERY_WSDL_LOCATION;
    private final static WebServiceException WSORDERQUERY_EXCEPTION;
    private final static QName WSORDERQUERY_QNAME = new QName("http://payat.ips.com.cn/WebService/OrderQuery", "WSOrderQuery");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://newpay.ips.com.cn/psfp-entry/services/order?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSORDERQUERY_WSDL_LOCATION = url;
        WSORDERQUERY_EXCEPTION = e;
    }

    public WSOrderQuery() {
        super(__getWsdlLocation(), WSORDERQUERY_QNAME);
    }

    public WSOrderQuery(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSORDERQUERY_QNAME, features);
    }

    public WSOrderQuery(URL wsdlLocation) {
        super(wsdlLocation, WSORDERQUERY_QNAME);
    }

    public WSOrderQuery(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSORDERQUERY_QNAME, features);
    }

    public WSOrderQuery(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSOrderQuery(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderQueryService
     */
    @WebEndpoint(name = "WSOrderQuerySoap")
    public OrderQueryService getWSOrderQuerySoap() {
        return super.getPort(new QName("http://payat.ips.com.cn/WebService/OrderQuery", "WSOrderQuerySoap"), OrderQueryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderQueryService
     */
    @WebEndpoint(name = "WSOrderQuerySoap")
    public OrderQueryService getWSOrderQuerySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://payat.ips.com.cn/WebService/OrderQuery", "WSOrderQuerySoap"), OrderQueryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSORDERQUERY_EXCEPTION!= null) {
            throw WSORDERQUERY_EXCEPTION;
        }
        return WSORDERQUERY_WSDL_LOCATION;
    }

}
