
package cn.com.ips.payat.webservice.tradequery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TradeQueryService", targetNamespace = "http://payat.ips.com.cn/WebService/TradeQuery")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface TradeQueryService {


    /**
     * 
     * @param tradeQuery
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://payat.ips.com.cn/WebService/TradeQuery/getTradeByMerBillNo")
    @WebResult(name = "getTradeByMerBillNoResult", partName = "getTradeByMerBillNoResult")
    public String getTradeByMerBillNo(
        @WebParam(name = "tradeQuery", partName = "tradeQuery")
        String tradeQuery);

    /**
     * 
     * @param tradeQuery
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://payat.ips.com.cn/WebService/TradeQuery/getTradeByTime")
    @WebResult(name = "getTradeByTimeResult", partName = "getTradeByTimeResult")
    public String getTradeByTime(
        @WebParam(name = "tradeQuery", partName = "tradeQuery")
        String tradeQuery);

    /**
     * 
     * @param tradeQuery
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://payat.ips.com.cn/WebService/TradeQuery/getTradeByNo")
    @WebResult(name = "getTradeByNoResult", partName = "getTradeByNoResult")
    public String getTradeByNo(
        @WebParam(name = "tradeQuery", partName = "tradeQuery")
        String tradeQuery);

}
