
package cn.com.ips.payat.webservice.refund;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RefundService", targetNamespace = "http://payat.ips.com.cn/WebService/Refund")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface RefundService {


    /**
     * 
     * @param refundInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://payat.ips.com.cn/WebService/Refund/refund")
    @WebResult(name = "refundResult", partName = "refundResult")
    public String refund(
        @WebParam(name = "refundInfo", partName = "refundInfo")
        String refundInfo);

}
