
package cn.com.ips.payat.webservice.scan;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSScan", targetNamespace = "http://payat.ips.com.cn/WebService/Scan", wsdlLocation = "https://thumbpay.e-years.com/psfp-webscan/services/scan?wsdl")
public class WSScan
    extends Service
{

    private final static URL WSSCAN_WSDL_LOCATION;
    private final static WebServiceException WSSCAN_EXCEPTION;
    private final static QName WSSCAN_QNAME = new QName("http://payat.ips.com.cn/WebService/Scan", "WSScan");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://thumbpay.e-years.com/psfp-webscan/services/scan?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSCAN_WSDL_LOCATION = url;
        WSSCAN_EXCEPTION = e;
    }

    public WSScan() {
        super(__getWsdlLocation(), WSSCAN_QNAME);
    }

    public WSScan(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSCAN_QNAME, features);
    }

    public WSScan(URL wsdlLocation) {
        super(wsdlLocation, WSSCAN_QNAME);
    }

    public WSScan(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSCAN_QNAME, features);
    }

    public WSScan(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSScan(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScanService
     */
    @WebEndpoint(name = "WSScanSoap")
    public ScanService getWSScanSoap() {
        return super.getPort(new QName("http://payat.ips.com.cn/WebService/Scan", "WSScanSoap"), ScanService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScanService
     */
    @WebEndpoint(name = "WSScanSoap")
    public ScanService getWSScanSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://payat.ips.com.cn/WebService/Scan", "WSScanSoap"), ScanService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSCAN_EXCEPTION!= null) {
            throw WSSCAN_EXCEPTION;
        }
        return WSSCAN_WSDL_LOCATION;
    }

}
