
package cn.com.ips.payat.webservice.quickpay;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSCollTrade", targetNamespace = "http://payat.ips.com.cn/WebService/CollTrade", wsdlLocation = "https://newpay.ips.com.cn/psfp-entry/services/coll?wsdl")
public class WSCollTrade
    extends Service
{

    private final static URL WSCOLLTRADE_WSDL_LOCATION;
    private final static WebServiceException WSCOLLTRADE_EXCEPTION;
    private final static QName WSCOLLTRADE_QNAME = new QName("http://payat.ips.com.cn/WebService/CollTrade", "WSCollTrade");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://newpay.ips.com.cn/psfp-entry/services/coll?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCOLLTRADE_WSDL_LOCATION = url;
        WSCOLLTRADE_EXCEPTION = e;
    }

    public WSCollTrade() {
        super(__getWsdlLocation(), WSCOLLTRADE_QNAME);
    }

    public WSCollTrade(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCOLLTRADE_QNAME, features);
    }

    public WSCollTrade(URL wsdlLocation) {
        super(wsdlLocation, WSCOLLTRADE_QNAME);
    }

    public WSCollTrade(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCOLLTRADE_QNAME, features);
    }

    public WSCollTrade(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCollTrade(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CollService
     */
    @WebEndpoint(name = "WSCollTradeSoap")
    public CollService getWSCollTradeSoap() {
        return super.getPort(new QName("http://payat.ips.com.cn/WebService/CollTrade", "WSCollTradeSoap"), CollService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CollService
     */
    @WebEndpoint(name = "WSCollTradeSoap")
    public CollService getWSCollTradeSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://payat.ips.com.cn/WebService/CollTrade", "WSCollTradeSoap"), CollService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCOLLTRADE_EXCEPTION!= null) {
            throw WSCOLLTRADE_EXCEPTION;
        }
        return WSCOLLTRADE_WSDL_LOCATION;
    }

}
